name: "🐛 Bug report"
description: Let us know about a bug!
labels: ['bug']
title: '[bug]'
body:
  - type: textarea
    id: problem
    attributes:
      label: Bug Report
      description: |
        Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior?
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce the Bug?
      description: |
        Please be minimal and precise as possible. If your repo/run is public, please include a URL so it is easier for us to investigate.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Screenshots or additional information and context?


  - type: textarea
    id: environment
    attributes:
      label: Environment Details?

  - type: input
    id: version
    attributes:
      label: Build version
      placeholder: vX.Y.Z
    validations:
      required: true


